# Generated by Django 4.0.6 on 2022-07-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
