# Generated by Django 4.0.6 on 2022-07-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_itinerary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
