# Generated by Django 4.0.6 on 2022-07-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_day_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='destination',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
