# Generated by Django 4.0.6 on 2022-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_image_alter_destination_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
