# Generated by Django 4.0.6 on 2022-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_itinerary_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cartegory',
                'verbose_name_plural': 'Cartegories',
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='cartegories',
            field=models.ManyToManyField(related_name='itineraries', to='destinations.cartegory'),
        ),
    ]
