# Generated by Django 4.0.6 on 2022-08-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_cartegory_itinerary_cartegories'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
