# Generated by Django 4.0.6 on 2022-08-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_day_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartegory',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
