# Generated by Django 4.0.6 on 2022-10-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_cartegory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
