# Generated by Django 4.0.6 on 2022-10-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_itinerary_is_upcoming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='cartegories',
        ),
        migrations.DeleteModel(
            name='Cartegory',
        ),
    ]
