# Generated by Django 4.0.6 on 2022-08-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipient',
            options={'verbose_name': 'Receipient', 'verbose_name_plural': 'Email Receipients'},
        ),
    ]
