# Generated by Django 4.0.6 on 2022-07-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_equipmenttype_equipment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'Equipment Type', 'verbose_name_plural': ' Types of Equipments'},
        ),
    ]
