# Generated by Django 4.0.6 on 2022-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_equipmenttype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
