# Generated by Django 4.0.6 on 2022-07-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_cartegory_itinerary_cartegories'),
        ('main', '0007_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_itineraries', to='destinations.itinerary')),
            ],
            options={
                'verbose_name': 'Featured Tour',
                'verbose_name_plural': 'Featured Tours',
            },
        ),
        migrations.CreateModel(
            name='FeaturedCartegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_itineraries', to='destinations.cartegory')),
            ],
            options={
                'verbose_name': 'Featured Cartegory',
                'verbose_name_plural': 'Featured Cartegories',
            },
        ),
    ]
