# Generated by Django 4.0.6 on 2022-10-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_featuredtour_featuredcartegory'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'YouTube Videos',
            },
        ),
    ]
