# Generated by Django 4.0.6 on 2022-10-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ytvideo',
            options={'verbose_name': 'YouTube Video', 'verbose_name_plural': 'YouTube Videos'},
        ),
    ]
